name: Go

on: [push]

#  :push
#    tags:
#    - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.7
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.7
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        wget https://github.com/caddyserver/xcaddy/releases/download/v0.1.5/xcaddy_0.1.5_linux_amd64.tar.gz
        tar -zxvf xcaddy_0.1.5_linux_amd64.tar.gz
        chmod +x xcaddy
        echo github.com/wxytjustb/caddy-plugins@${GITHUB_REF##*/}

    - name: Test
      run: echo '自动化测试'

    - name: Build
      run: |
        GOOS=linux ./xcaddy build --with github.com/wxytjustb/caddy-plugins@${GITHUB_REF##*/}

    - name: Publish Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: caddy
        path: caddy

