name: Go

on:
  push:
    tags:
    - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14.7
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.7
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        curl https://github.com/caddyserver/xcaddy/releases/download/v0.1.5/xcaddy_0.1.5_linux_amd64.tar.gz
        tar -zxvf xcaddy_0.1.5_linux_amd64.tar.gz
        cp xcaddy_0.1.5_linux_amd64/xcaddy /usr/local/bin/
        echo github.com/wxytjustb/caddy-plugins@${{ github.ref }}


    - name: Build
      run: xcaddy build --with github.com/wxytjustb/caddy-plugins@${{ github.ref }}

    - name: Test
      run: echo 'This is Test Code'
